In [43]:
import numpy as np
from numpy.linalg import eigh, norm

In [44]:
A = np.array([[2,0,0],
              [2,1,0],
              [0,-2,0]])

In [45]:
A

array([[ 2,  0,  0],
       [ 2,  1,  0],
       [ 0, -2,  0]])

In [46]:
ATA = A.T.dot(A)


In [47]:
ATA 

array([[8, 2, 0],
       [2, 5, 0],
       [0, 0, 0]])

In [48]:
eigenvalues_ATA, eigenvectors_ATA = eigh(ATA)

In [49]:
eigenvalues_ATA, eigenvectors_ATA

(array([0., 4., 9.]),
 array([[ 0.        ,  0.4472136 , -0.89442719],
        [ 0.        , -0.89442719, -0.4472136 ],
        [ 1.        ,  0.        , -0.        ]]))

In [50]:
sorted_indices = np.argsort(eigenvalues_ATA)[::-1]
eigenvalues_ATA = eigenvalues_ATA[sorted_indices]
eigenvectors_ATA = eigenvectors_ATA[:, sorted_indices]

In [51]:
singular_values = np.sqrt(eigenvalues_ATA)

In [52]:
singular_values

array([3., 2., 0.])

In [53]:
S = np.zeros_like(A, dtype=float)
S[:A.shape[0], :A.shape[1]] = np.diag(singular_values)

In [54]:
S[:A.shape[0], :A.shape[1]]

array([[3., 0., 0.],
       [0., 2., 0.],
       [0., 0., 0.]])

In [55]:
U = A.dot(eigenvectors_ATA)

In [56]:
U /= norm(U, axis=0)

C:\Users\avinash\AppData\Local\Temp\ipykernel_20280\4239885122.py:1: RuntimeWarning: invalid value encountered in divide
  U /= norm(U, axis=0)


In [57]:
Vt = eigenvectors_ATA.T



In [59]:
print("Matrix U (3x3):")
print(U)
print("\nMatrix S (3x3):")
print(S)
print("\nMatrix Vt (3x3):")
print(Vt)

Matrix U (3x3):
[[-0.59628479  0.4472136          nan]
 [-0.74535599  0.                 nan]
 [ 0.2981424   0.89442719         nan]]

Matrix S (3x3):
[[3. 0. 0.]
 [0. 2. 0.]
 [0. 0. 0.]]

Matrix Vt (3x3):
[[-0.89442719 -0.4472136  -0.        ]
 [ 0.4472136  -0.89442719  0.        ]
 [ 0.          0.          1.        ]]
